[workspace]
members = ["rc5-rs"]

resolver = "2"

[workspace.package]
version = "3.0.14"
authors = ["Syed-Anees <syedanees816@gmail.com>"]
repository = "https://github.com/MetaGravity/Quark"
edition = "2024"
publish = false
rust-version = "1.85.0"