[package]
name = "rc5-rs"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
rand = "0.8"
thiserror = "2.0.12"
hex = "0.4.3"
